name: Feature - Nouvelle fonctionnalité
description: "Proposer une nouvelle fonctionnalité"
title: "[BTS-XX] feat : "
labels:
  - feature
  - ready
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ### Objectif
        Décrire la nouvelle fonctionnalité.

  - type: textarea
    attributes:
      label: Solution proposée
      description: Comment implémenter la fonctionnalité
      placeholder: >
        Exemple :
        * Ajouter `nouvelle_fonction.py`
        * Mettre à jour `main.py` pour gérer le nouveau mode

  - type: checkboxes
    attributes:
      label: Critères d’acceptation
      description: Pour considérer la fonctionnalité terminée
      options:
        - "Fonctionnalité implémentée"
        - "Tests unitaires ajoutés"
        - "CI verte"

  - type: input
    attributes:
      label: Lien
      description: Lien vers issue ou PR associée
      placeholder: Closes #15
